[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "ebay.metadata"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/eBay", "Area/E-Commerce", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ebay.metadata"

[build-options]
observabilityIncluded = true

