// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The Metadata API provides crucial configuration details necessary for managing listings across various eBay marketplaces. This includes retrieving detailed eBay category listing policies, such as supported item conditions and multiple-variation structures; accessing sales tax jurisdiction information for setting up tax tables in supported countries; and obtaining hazardous material and product safety label data for regulatory compliance in listing flows. The API is essential for sellers and developers needing up-to-date, marketplace-specific policy and jurisdictional information to accurately create and manage their listings.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.ebay.com/sell/metadata/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get automotive parts compatibility policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # Note: Only the following eBay marketplaces support automotive parts compatibility:
    # - EBAY_MOTORS_US
    # - EBAY_AU
    # - EBAY_CA
    # - EBAY_DE
    # - EBAY_ES
    # - EBAY_FR
    # - EBAY_GB
    # - EBAY_IT
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved automotive parts compatibility policies 
    remote isolated function getAutomotivePartsCompatibilityPolicies(string marketplaceId, GetAutomotivePartsCompatibilityPoliciesHeaders headers = {}, *GetAutomotivePartsCompatibilityPoliciesQueries queries) returns AutomotivePartsCompatibilityPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_automotive_parts_compatibility_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get category policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved category policies 
    remote isolated function getCategoryPolicies(string marketplaceId, GetCategoryPoliciesHeaders headers = {}, *GetCategoryPoliciesQueries queries) returns CategoryPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_category_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get classified ad policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Marketplace ID values for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved classified ad policies 
    remote isolated function getClassifiedAdPolicies(string marketplaceId, GetClassifiedAdPoliciesHeaders headers = {}, *GetClassifiedAdPoliciesQueries queries) returns ClassifiedAdPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_classified_ad_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get marketplace currencies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which currency information is retrieved.
    # See the Marketplace ID values type for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + return - The retrieved currencies 
    remote isolated function getCurrencies(string marketplaceId, GetCurrenciesHeaders headers = {}) returns GetCurrenciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_currencies`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get extended producer responsibility policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information shall be retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved extended producer responsibility policies 
    remote isolated function getExtendedProducerResponsibilityPolicies(string marketplaceId, GetExtendedProducerResponsibilityPoliciesHeaders headers = {}, *GetExtendedProducerResponsibilityPoliciesQueries queries) returns ExtendedProducerResponsibilityPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_extended_producer_responsibility_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get hazardous materials labels
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which hazardous materials label information shall be retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + return - The retrieved hazardous materials labels 
    remote isolated function getHazardousMaterialsLabels(string marketplaceId, GetHazardousMaterialsLabelsHeaders headers = {}) returns HazardousMaterialDetailsResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_hazardous_materials_labels`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get item condition policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved item condition policies 
    remote isolated function getItemConditionPolicies(string marketplaceId, GetItemConditionPoliciesHeaders headers = {}, *GetItemConditionPoliciesQueries queries) returns ItemConditionPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_item_condition_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get listing structure policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved listing structure policies 
    remote isolated function getListingStructurePolicies(string marketplaceId, GetListingStructurePoliciesHeaders headers = {}, *GetListingStructurePoliciesQueries queries) returns ListingStructurePolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_listing_structure_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get listing type policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved listing type policies 
    remote isolated function getListingTypePolicies(string marketplaceId, GetListingTypePoliciesHeaders headers = {}, *GetListingTypePoliciesQueries queries) returns ListingTypePoliciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_listing_type_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get minimum listing price policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which minimum listing price policy information will be retrieved.
    # See Marketplace ID values for a list of supported eBay marketplace ID values.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved minimum listing price policies 
    remote isolated function getMinimumListingPricePolicies(string marketplaceId, map<string|string[]> headers = {}) returns GetMinimumListingPricePoliciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_minimum_listing_price_policies`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get eBay Motors listing policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved motors listing policies 
    remote isolated function getMotorsListingPolicies(string marketplaceId, GetMotorsListingPoliciesHeaders headers = {}, *GetMotorsListingPoliciesQueries queries) returns MotorsListingPoliciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_motors_listing_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get negotiated price policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved negotiated price policies 
    remote isolated function getNegotiatedPricePolicies(string marketplaceId, GetNegotiatedPricePoliciesHeaders headers = {}, *GetNegotiatedPricePoliciesQueries queries) returns NegotiatedPricePolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_negotiated_price_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get product safety labels
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values. See the following note for exceptions.Note: This method is not supported in the EBAY_HK, EBAY_MY, EBAY_TW, or EBAY_PH marketplaces.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved product safety labels 
    remote isolated function getProductSafetyLabels(string marketplaceId, map<string|string[]> headers = {}) returns ProductSafetyLabelsResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_product_safety_labels`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get regulatory policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information shall be retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values.Note: This method is not supported in the EBAY_HK, EBAY_MY, EBAY_TW, or EBAY_PH marketplaces.
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved regulatory policies 
    remote isolated function getRegulatoryPolicies(string marketplaceId, GetRegulatoryPoliciesHeaders headers = {}, *GetRegulatoryPoliciesQueries queries) returns RegulatoryPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_regulatory_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get return policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved return policies 
    remote isolated function getReturnPolicies(string marketplaceId, GetReturnPoliciesHeaders headers = {}, *GetReturnPoliciesQueries queries) returns ReturnPolicyResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_return_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get shipping policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved shipping policies 
    remote isolated function getShippingPolicies(string marketplaceId, GetShippingPoliciesHeaders headers = {}, *GetShippingPoliciesQueries queries) returns ShippingPoliciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_shipping_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get site visibility policies
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which policy information is retrieved.
    # See Request Headers for a list of supported eBay marketplace ID values
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The retrieved site visibility policies 
    remote isolated function getSiteVisibilityPolicies(string marketplaceId, GetSiteVisibilityPoliciesHeaders headers = {}, *GetSiteVisibilityPoliciesQueries queries) returns SiteVisibilityPoliciesResponse|error? {
        string resourcePath = string `/marketplace/${getEncodedUri(marketplaceId)}/get_site_visibility_policies`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get compatibilities by specification
    #
    # + headers - Headers to be sent with the request 
    # + payload - This type defines the properties and specifications to use to search for compatibilities 
    # + return - The retrieved compatibilities by specification 
    remote isolated function getCompatibilitiesBySpecification(GetCompatibilitiesBySpecificationHeaders headers, SpecificationRequest payload) returns SpecificationResponse|error? {
        string resourcePath = string `/compatibilities/get_compatibilities_by_specification`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get compatibility property names
    #
    # + headers - Headers to be sent with the request 
    # + payload - This type defines the properties used to retrieve compatibility property names 
    # + return - The retrieved compatibility property names 
    remote isolated function getCompatibilityPropertyNames(GetCompatibilityPropertyNamesHeaders headers, PropertyNamesRequest payload) returns PropertyNamesResponse|error? {
        string resourcePath = string `/compatibilities/get_compatibility_property_names`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get compatibility property values
    #
    # + headers - Headers to be sent with the request 
    # + payload - This type defines the category ID and property name for which to retrieve values 
    # + return - The retrieved compatibility property values 
    remote isolated function getCompatibilityPropertyValues(GetCompatibilityPropertyValuesHeaders headers, PropertyValuesRequest payload) returns PropertyValuesResponse|error? {
        string resourcePath = string `/compatibilities/get_compatibility_property_values`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get multiple compatibility property values
    #
    # + headers - Headers to be sent with the request 
    # + payload - This type defines the category ID and property names for which to retrieve values 
    # + return - The retrieved multi compatibility property values 
    remote isolated function getMultiCompatibilityPropertyValues(GetMultiCompatibilityPropertyValuesHeaders headers, MultiCompatibilityPropertyValuesRequest payload) returns MultiCompatibilityPropertyValuesResponse|error? {
        string resourcePath = string `/compatibilities/get_multi_compatibility_property_values`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get product compatibilities
    #
    # + headers - Headers to be sent with the request 
    # + payload - This type defines properties for which to find compatibilities 
    # + return - The retrieved product compatibilities 
    remote isolated function getProductCompatibilities(GetProductCompatibilitiesHeaders headers, ProductRequest payload) returns ProductResponse|error? {
        string resourcePath = string `/compatibilities/get_product_compatibilities`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get excluded shipping locations
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which excluded shipping locations information is retrieved.
    # See Marketplace ID values for supported eBay marketplace ID values.
    # Note: When listing the items on the French Canada, French Belgium, and Dutch Belgium marketplaces, also set the Accept-Language header as needed.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved exclude shipping locations 
    remote isolated function getExcludeShippingLocations(string marketplaceId, GetExcludeShippingLocationsHeaders headers = {}) returns ShippingExcludeLocationResponse|error {
        string resourcePath = string `/shipping/marketplace/${getEncodedUri(marketplaceId)}/get_exclude_shipping_locations`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get handling times
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which handling times information is retrieved.
    # See Marketplace ID values for supported eBay marketplace ID values.
    # Note: When listing the items on the French Canada, French Belgium, and Dutch Belgium marketplaces, also set the Accept-Language header as needed.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved handling times 
    remote isolated function getHandlingTimes(string marketplaceId, GetHandlingTimesHeaders headers = {}) returns ShippingHandlingTimeResponse|error {
        string resourcePath = string `/shipping/marketplace/${getEncodedUri(marketplaceId)}/get_handling_times`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get shipping carriers
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which shipping carriers information is retrieved.
    # See Marketplace ID values for supported eBay marketplace ID values.
    # Note: When listing the items on the French Canada, French Belgium, and Dutch Belgium marketplaces, also set the Accept-Language header as needed.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved shipping carriers 
    remote isolated function getShippingCarriers(string marketplaceId, GetShippingCarriersHeaders headers = {}) returns ShippingCarrierResponse|error {
        string resourcePath = string `/shipping/marketplace/${getEncodedUri(marketplaceId)}/get_shipping_carriers`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get shipping locations
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which shipping locations information is retrieved.
    # See Marketplace ID values for supported eBay marketplace ID values.
    # Note: When listing the items on the French Canada, French Belgium, and Dutch Belgium marketplaces, also set the Accept-Language header as needed.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved shipping locations 
    remote isolated function getShippingLocations(string marketplaceId, GetShippingLocationsHeaders headers = {}) returns ShippingLocationResponse|error {
        string resourcePath = string `/shipping/marketplace/${getEncodedUri(marketplaceId)}/get_shipping_locations`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get shipping services
    #
    # + marketplaceId - This path parameter specifies the eBay marketplace for which shipping services information is retrieved.
    # See Marketplace ID values for supported eBay marketplace ID values.
    # Note: When listing the items on the French Canada, French Belgium, and Dutch Belgium marketplaces, also set the Accept-Language header as needed.
    # + headers - Headers to be sent with the request 
    # + return - The retrieved shipping services 
    remote isolated function getShippingServices(string marketplaceId, GetShippingServicesHeaders headers = {}) returns ShippingServiceResponse|error {
        string resourcePath = string `/shipping/marketplace/${getEncodedUri(marketplaceId)}/get_shipping_services`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get sales tax jurisdictions
    #
    # + countryCode - This path parameter specifies the two-letter ISO 3166 country code for the country whose jurisdictions you want to retrieve.
    # Note: Sales-tax tables are available only for the US and Canada marketplaces. Therefore, the only supported values are:
    # - US
    # - CA
    # + headers - Headers to be sent with the request 
    # + return - The retrieved sales tax jurisdictions 
    remote isolated function getSalesTaxJurisdictions(string countryCode, map<string|string[]> headers = {}) returns SalesTaxJurisdictions|error {
        string resourcePath = string `/country/${getEncodedUri(countryCode)}/sales_tax_jurisdiction`;
        return self.clientEp->get(resourcePath, headers);
    }
}
